name: Keep my Duolingo streak

on:
  push:
    branches:
      - main
#   schedule:
#     - cron: '0 9 * * *'

env:
  DUOLINGO_USER_ID: ${{ secrets.DUOLINGO_USER_ID }}
  DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ./
