name: Keep my Duolingo streak

on:
  push:
    branches:
      - main
#   schedule:
#     - cron: '0 9 * * *'

env:
  DUOLINGO_USER_ID: '123'
  DUOLINGO_JWT: 'abc'

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
